from PyQt5.QtCore import Qt

DICT_CLIENT = "client"
DICT_PRODUCT = "product"
DICT_PRICE = "price"

ACTION_NO_ACTION = 0
ACTION_ADD = 1
ACTION_MODIFY = 2
ACTION_DELETE = 3

COLOR_PAYMENT_FINISHED = 0xff92D050
COLOR_PAYMENT_PENDING = 0xffFF6767

COLOR_PRIORITY_LOW = 0xffAABF00
COLOR_PRIORITY_MEDIUM = 0xffFFFF00
COLOR_PRIORITY_HIGH = 0xffFFFF00

COLOR_ARRIVAL_PENDING = 0xffFF6767
COLOR_ARRIVAL_PARTIAL = 0xffFF9462
COLOR_ARRIVAL_RECLAIM = 0xffFF6767

RoleNodeId = Qt.UserRole + 1
RoleClient = RoleNodeId + 1
RoleProduct = RoleClient + 1
